### ISSUE TITLE
有丢失log的情况，我使用的时候法案，有的方法里面的代码执行了，但是log并没有打印

### ISSUE THREAD

**Issue by woniu0936** [Blankj/ALog#1]
我的使用环境线程切换比较频繁

**Comment by Blankj** [comment]
logcat中吗，还是file，你可以前面执行一句正常的log，然后调用我的，然后对比一下是否我的有丢失，如果正常的log没丢失，我的丢失了那就是我的问题

**Comment by woniu0936** [comment]
抱歉，回复晚了，是IDE吧log给吞了
