### ISSUE TITLE
去掉final呗

### ISSUE THREAD

**Issue by djun100** [Blankj/ALog#11]
我想放到个人工具库里，直接依赖这个库，然后用子类来扩展。不然还要复制一遍

**Comment by Blankj** [comment]
你要是想那样拓展那你就拷贝过去就好了，不要引用我的库好了，用子类 log 的堆栈可能会出问题的，初始化 setStackOffset 可以解决。写成 final 就是为了杜绝你们继承哈，因为工具类已经是静态了，和对象其实没有关系，所以也就没有必要继承，你要拓展推荐你可以自己再写个类暴露你需要的 api 出来，然后 api 里可以调用我的 ALog
