### ISSUE TITLE
是否可以支持日志按类别输出到不同文件

### ISSUE THREAD

**Issue by yicm** [Blankj/ALog#15]
如
- error，`自定义名字+error.log`
- debug, `自定义名字+debug.log`
之类的。功能如下：
- 可设定是否分级别将日志输出到不同文件
- 可设定保存不同级别日志的文件名，默认值为`日期+级别.log`

**Comment by djun100** [comment]
@yicm 可以参考我对ALog的扩展
https://github.com/djun100/UtilAndroid/blob/master/utilAndroid/src/main/java/com/cy/io/Log.java

**Comment by yicm** [comment]
@djun100 实现很简单哈。。只是建议。
