### ISSUE TITLE
android 7.0 日志打印不出来，华为畅享7

### ISSUE THREAD

**Issue by zjianflys** [Blankj/ALog#6]
10-18 11:00:00.748 29539-29539/? I/art: Late-enabling -Xcheck:jni
10-18 11:00:00.896 29539-29539/com.blankj.alog W/System: ClassLoader referenced unknown path: /data/app/com.blankj.alog-1/lib/arm

报了这个错,但是写文件是可以，难道是我的开发工具有问题.....我换成模拟器日志可以正常打印....

**Comment by Blankj** [comment]
打不了的d级别的吧，你换成e试试

**Comment by zjianflys** [comment]
我测试了一下v,d级别的不行,是什么原因导致的？  其他几个级别的是没得问题,谢谢哈

**Comment by Blankj** [comment]
因为你手机的问题，你手机默认日志就不支持v，d级别

**Comment by zjianflys** [comment]
恩  ，对头就是这个原因 我直接用Log.d   也打不出来 .......    谢谢你哈  正在看你的代码   很赞....
