### ISSUE TITLE
想请问下支持android studio的是怎么实现的

### ISSUE THREAD

**Issue by kaleai** [Blankj/ALog#9]
首先真的要佩服一下，一个类就搞定了这么多功能。readme中有提到兼容as，想问下是怎么做到的呢？

**Comment by Blankj** [comment]
之前调用 Alog.x 中间会调用多次 Log.x 所以会出现 AS 3.x 版本同 tag 合并的问题，可以参考我[这篇文章](https://blankj.com/2018/04/12/solve-logcat/) 看一下图片就知道怎么解决的了

**Comment by kaleai** [comment]
谢谢大神！

**Comment by Blankj** [comment]
不才不才 也是看过你很多技术文章的啦
